sudo: required
services:
  - docker

before_install:
  - docker build -t itykhan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true itykhan/react-test npm test

after_success:
  - docker build -t itykhan/multi-client ./client
  - docker build -t itykhan/multi-nginx ./nginx
  - docker build -t itykhan/multi-server ./server
  - docker build -t itykhan/multi-worker ./worker
  #login to the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push itykhan/multi-client
  - docker push itykhan/multi-nginx
  - docker push itykhan/multi-server
  - docker push itykhan/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-630632899966
    docker_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY