sudo: required
services:
  - docker

before_install:
  - docker build -i itykhan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t itykhan/multi-client ./client
  - docker build -t itykhan/multi-nginx ./nginx
  - docker build -t itykhan/multi-server ./server
  - docker build -i itykhan/multi-worker ./worker
  #login to the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push itykhan/multi-client
  - docker push itykhan/multi-nginx
  - docker push itykhan/multi-server
  - docker push itykhan/multi-worker